# Generated by Django 3.2.5 on 2022-02-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_detail', models.CharField(max_length=1000)),
                ('product_price', models.IntegerField()),
                ('product_image', models.FileField(upload_to='product')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
